#! /usr/bin/env python
# -*- python -*-

import lhapdf

sets = []
for s in lhapdf.availablePDFSets():
    i = lhapdf.getPDFSet(s)
    sets.append([i.lhapdfID, i.name, i.dataversion])
for id, name, version in sorted(sets):
    if id > 0:
        print id, name, version
